"""initial schema

Revision ID: 1054cb59ce6b
Revises: 
Create Date: 2026-02-17 16:41:24.041476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1054cb59ce6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.Column('can_access_inbound', sa.Boolean(), nullable=True),
    sa.Column('can_access_distribution', sa.Boolean(), nullable=True),
    sa.Column('can_access_data_entry', sa.Boolean(), nullable=True),
    sa.Column('can_access_dashboard', sa.Boolean(), nullable=True),
    sa.Column('can_access_profile', sa.Boolean(), nullable=True),
    sa.Column('can_access_outbound', sa.Boolean(), nullable=True),
    sa.Column('can_access_admin_panel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index('ix_warehouses_active_name', ['is_active', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=True)

    op.create_table('data_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('warehouse', sa.String(length=150), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pit_account_name', sa.String(length=150), nullable=True),
    sa.Column('parcels_count', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=True),
    sa.Column('distribution_type', sa.String(length=50), nullable=True),
    sa.Column('data_entry_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('beneficiaries_image', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_entries_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entries_distribution_type'), ['distribution_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entries_pit_account_name'), ['pit_account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entries_warehouse'), ['warehouse'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_entries_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_dataentry_creator_date', ['created_by_user_id', 'entry_date'], unique=False)
        batch_op.create_index('ix_dataentry_warehouse_date', ['warehouse_id', 'entry_date'], unique=False)

    op.create_table('distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('dist_date', sa.Date(), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('dist_point_neighbourhood', sa.String(length=150), nullable=True),
    sa.Column('dist_point', sa.String(length=150), nullable=True),
    sa.Column('focal_point_name', sa.String(length=150), nullable=True),
    sa.Column('beneficiaries_hhs', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_members', sa.Integer(), nullable=True),
    sa.Column('nr_parcels', sa.Integer(), nullable=True),
    sa.Column('whf_bags', sa.Integer(), nullable=True),
    sa.Column('date_bars', sa.Integer(), nullable=True),
    sa.Column('heb_piece', sa.Integer(), nullable=True),
    sa.Column('add_new_item', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dist_image', sa.String(length=255), nullable=True),
    sa.Column('data_entry_name', sa.String(length=100), nullable=True),
    sa.Column('whf_unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('date_bars_unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('heb_unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('parcels_unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('whf_mt', sa.Float(), nullable=True),
    sa.Column('date_bars_mt', sa.Float(), nullable=True),
    sa.Column('heb_mt', sa.Float(), nullable=True),
    sa.Column('parcels_mt', sa.Float(), nullable=True),
    sa.Column('whf_damage_units', sa.Integer(), nullable=True),
    sa.Column('date_bars_damage_units', sa.Integer(), nullable=True),
    sa.Column('heb_damage_units', sa.Integer(), nullable=True),
    sa.Column('parcels_damage_units', sa.Integer(), nullable=True),
    sa.Column('is_merged', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribution_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_distribution_creator_date', ['created_by_user_id', 'dist_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_dist_date'), ['dist_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_dist_point'), ['dist_point'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_governorate'), ['governorate'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_is_merged'), ['is_merged'], unique=False)
        batch_op.create_index('ix_distribution_warehouse_date', ['warehouse_id', 'dist_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arabic_first_name', sa.String(length=100), nullable=True),
    sa.Column('arabic_second_name', sa.String(length=100), nullable=True),
    sa.Column('arabic_third_name', sa.String(length=100), nullable=True),
    sa.Column('arabic_family_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('third_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=9), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('gov', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=150), nullable=True),
    sa.Column('nearby', sa.String(length=150), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound',
    sa.Column('supervisor_name', sa.String(length=120), nullable=True),
    sa.Column('inbound_entry_name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fdp', sa.String(length=120), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('governorate', sa.String(length=120), nullable=True),
    sa.Column('waybill_number', sa.String(length=50), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('si_number', sa.String(length=50), nullable=True),
    sa.Column('pallets_count', sa.Integer(), nullable=True),
    sa.Column('units_per_pallet', sa.Integer(), nullable=True),
    sa.Column('unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('qty_mt', sa.Float(), nullable=True),
    sa.Column('net_boxes', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('damage_count', sa.Integer(), nullable=True),
    sa.Column('inbound_datetime', sa.DateTime(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('empty_pallets_count', sa.Integer(), nullable=False),
    sa.Column('waybill_image', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_commodity'), ['commodity'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_inbound_creator_datetime', ['created_by_user_id', 'inbound_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_fdp'), ['fdp'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_inbound_datetime'), ['inbound_datetime'], unique=False)
        batch_op.create_index('ix_inbound_warehouse_date', ['warehouse_id', 'date'], unique=False)
        batch_op.create_index('ix_inbound_warehouse_datetime', ['warehouse_id', 'inbound_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_waybill_number'), ['waybill_number'], unique=False)

    op.create_table('outbound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fdp', sa.String(length=128), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('governorate', sa.String(length=128), nullable=True),
    sa.Column('waybill_number', sa.String(length=64), nullable=False),
    sa.Column('commodity', sa.String(length=32), nullable=False),
    sa.Column('si_number', sa.String(length=64), nullable=True),
    sa.Column('pallets_count', sa.Integer(), nullable=True),
    sa.Column('empty_pallets', sa.Integer(), nullable=True),
    sa.Column('units_per_pallet', sa.Integer(), nullable=True),
    sa.Column('net_boxes', sa.Integer(), nullable=True),
    sa.Column('unit_weight_kg', sa.Float(), nullable=True),
    sa.Column('qty_mt', sa.Float(), nullable=True),
    sa.Column('damage_count', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=64), nullable=True),
    sa.Column('supervisor_name', sa.String(length=128), nullable=True),
    sa.Column('outbound_entry_name', sa.String(length=128), nullable=True),
    sa.Column('outbound_datetime', sa.DateTime(), nullable=True),
    sa.Column('waybill_image', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_commodity'), ['commodity'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_outbound_creator_datetime', ['created_by_user_id', 'outbound_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_fdp'), ['fdp'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_outbound_datetime'), ['outbound_datetime'], unique=False)
        batch_op.create_index('ix_outbound_warehouse_date', ['warehouse_id', 'date'], unique=False)
        batch_op.create_index('ix_outbound_warehouse_datetime', ['warehouse_id', 'outbound_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_waybill_number'), ['waybill_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_waybill_number'))
        batch_op.drop_index(batch_op.f('ix_outbound_warehouse_id'))
        batch_op.drop_index('ix_outbound_warehouse_datetime')
        batch_op.drop_index('ix_outbound_warehouse_date')
        batch_op.drop_index(batch_op.f('ix_outbound_outbound_datetime'))
        batch_op.drop_index(batch_op.f('ix_outbound_fdp'))
        batch_op.drop_index(batch_op.f('ix_outbound_date'))
        batch_op.drop_index('ix_outbound_creator_datetime')
        batch_op.drop_index(batch_op.f('ix_outbound_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_commodity'))

    op.drop_table('outbound')
    with op.batch_alter_table('inbound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_waybill_number'))
        batch_op.drop_index(batch_op.f('ix_inbound_warehouse_id'))
        batch_op.drop_index('ix_inbound_warehouse_datetime')
        batch_op.drop_index('ix_inbound_warehouse_date')
        batch_op.drop_index(batch_op.f('ix_inbound_inbound_datetime'))
        batch_op.drop_index(batch_op.f('ix_inbound_fdp'))
        batch_op.drop_index(batch_op.f('ix_inbound_date'))
        batch_op.drop_index('ix_inbound_creator_datetime')
        batch_op.drop_index(batch_op.f('ix_inbound_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_commodity'))

    op.drop_table('inbound')
    op.drop_table('employees')
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_warehouse_id'))
        batch_op.drop_index('ix_distribution_warehouse_date')
        batch_op.drop_index(batch_op.f('ix_distribution_is_merged'))
        batch_op.drop_index(batch_op.f('ix_distribution_governorate'))
        batch_op.drop_index(batch_op.f('ix_distribution_dist_point'))
        batch_op.drop_index(batch_op.f('ix_distribution_dist_date'))
        batch_op.drop_index('ix_distribution_creator_date')
        batch_op.drop_index(batch_op.f('ix_distribution_created_by_user_id'))

    op.drop_table('distribution')
    with op.batch_alter_table('data_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_dataentry_warehouse_date')
        batch_op.drop_index('ix_dataentry_creator_date')
        batch_op.drop_index(batch_op.f('ix_data_entries_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_data_entries_warehouse'))
        batch_op.drop_index(batch_op.f('ix_data_entries_pit_account_name'))
        batch_op.drop_index(batch_op.f('ix_data_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_data_entries_distribution_type'))
        batch_op.drop_index(batch_op.f('ix_data_entries_created_by_user_id'))

    op.drop_table('data_entries')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))
        batch_op.drop_index(batch_op.f('ix_warehouses_is_active'))
        batch_op.drop_index(batch_op.f('ix_warehouses_created_at'))
        batch_op.drop_index('ix_warehouses_active_name')

    op.drop_table('warehouses')
    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.drop_table('products')
    op.drop_table('archive')
    # ### end Alembic commands ###
